/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "pendingEmail.verify": [
        {
            "name": "token",
            "required": true
        }
    ],
    "app.dashboard": [],
    "app.placeholder": [],
    "home": [],
    "app.settings": [],
    "app.profile.edit": [],
    "app.profile.update": [],
    "app.profile.destroy": [],
    "app.profile.resend-verification-email": [],
    "app.profile.clear-pending-mail-address": [],
    "app.password.edit": [],
    "app.password.update": [],
    "app.api-tokens.index": [],
    "app.api-tokens.create": [],
    "app.api-tokens.store": [],
    "app.api-tokens.delete": [
        {
            "name": "token",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
